---
title: "Airport Popularity"
author: "Lauren Meyer, Neamat Sabry, Carol Milton"
date: "4/30/2019"
output: 
  html_document:
    code_folding: hide
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(RMySQL)
db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "airlines")
knitr::opts_chunk$set(connection = db, max.print = 20)
```

Neamt's attempting attempts.

## Top 10 Airports With the Most Planes Flying From

```{sql}
SELECT a.origin, 
	COUNT(a.carrier) AS flight_count, airports.name
FROM airlines.flights a
LEFT JOIN airports ON airports.faa = a.origin
WHERE year = 2017
GROUP BY a.origin
ORDER BY flight_count DESC
LIMIT 0,10;
```

### With the lowest being...
```{sql}
SELECT a.origin, 
	COUNT(a.carrier) AS flight_count, airports.name
FROM airlines.flights a
LEFT JOIN airports ON airports.faa = a.origin
WHERE year = 2017
GROUP BY a.origin
ORDER BY flight_count
LIMIT 1;
```

## Top 10 Airports With the Most Planes Flying To

```{sql}
SELECT a.dest, 
	COUNT(a.carrier) AS flight_count, airports.name
FROM airlines.flights a
LEFT JOIN airports ON airports.faa = a.origin
WHERE year = 2017
GROUP BY a.dest
ORDER BY flight_count DESC
LIMIT 0,10;
```

### With the lowest being...
```{sql}
SELECT a.dest, 
	COUNT(a.carrier) AS flight_count, airports.name
FROM airlines.flights a 
LEFT JOIN airports ON airports.faa = a.origin
WHERE year = 2017
GROUP BY a.dest
ORDER BY flight_count
LIMIT 1;
```

GitHub repository.^[https://github.com/LyraDusk/mp4.git]